events {}

http {
	server {
		listen 80;

		location ~ /.well-known/acme-challenge {
			root /var/www/certbot;
		}

		return 301 https://$host$request_uri;
	}

	server {
		listen 443 ssl http2;

		ssl_certificate /etc/letsencrypt/live/artobium.net/fullchain.pem;
		ssl_certificate /etc/letsencrypt/live/artobium.net/privkey.pem;
		server_name artobium.net

		location / {
      		proxy_pass http://server:8080; 
      		proxy_set_header Host $host;
      		proxy_set_header X-Real-IP $remote_addr;
      		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	}

		location ~ /.well-known/acme-challenge {
			root /var/www/certbot;
		}
		
	}
}